#ifndef SYNTH_PARAMS_H
#define SYNTH_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

// Central registry for every UI-visible parameter. Keep values stable so that
// preset files and automation data remain compatible across versions.
typedef enum ParamId {
    PARAM_MASTER_VOLUME = 0,
    PARAM_TEMPO,

    // Oscillator section
    PARAM_OSC1_WAVE,
    PARAM_OSC1_COARSE,
    PARAM_OSC1_FINE,
    PARAM_OSC1_PWM,
    PARAM_OSC1_SUB_MIX,
    PARAM_OSC1_SYNC,

    PARAM_OSC2_WAVE,
    PARAM_OSC2_COARSE,
    PARAM_OSC2_FINE,
    PARAM_OSC2_PWM,
    PARAM_OSC2_SUB_MIX,
    PARAM_OSC2_SYNC,

    PARAM_OSC_MIX,
    PARAM_PORTAMENTO_TIME,
    PARAM_LEGATO_MODE,

    // Filter section
    PARAM_FILTER_MODE,
    PARAM_FILTER_CUTOFF,
    PARAM_FILTER_RESONANCE,
    PARAM_FILTER_DRIVE,
    PARAM_FILTER_KEYTRACK,
    PARAM_FILTER_ENV_AMOUNT,

    // Envelope section
    PARAM_ENV_AMP_ATTACK,
    PARAM_ENV_AMP_DECAY,
    PARAM_ENV_AMP_SUSTAIN,
    PARAM_ENV_AMP_RELEASE,

    PARAM_ENV_FILTER_ATTACK,
    PARAM_ENV_FILTER_DECAY,
    PARAM_ENV_FILTER_SUSTAIN,
    PARAM_ENV_FILTER_RELEASE,

    PARAM_ENV_PITCH_ATTACK,
    PARAM_ENV_PITCH_DECAY,
    PARAM_ENV_PITCH_SUSTAIN,
    PARAM_ENV_PITCH_RELEASE,

    // LFO / modulation
    PARAM_LFO1_RATE,
    PARAM_LFO1_DEPTH,
    PARAM_LFO1_DEST,
    PARAM_LFO1_SYNC,
    PARAM_LFO1_FADE,

    PARAM_LFO2_RATE,
    PARAM_LFO2_DEPTH,
    PARAM_LFO2_DEST,
    PARAM_LFO2_SYNC,
    PARAM_LFO2_FADE,

    // FX / output
    PARAM_FX_DISTORTION_ENABLED,
    PARAM_FX_DISTORTION_DRIVE,
    PARAM_FX_DISTORTION_MIX,
    PARAM_FX_CHORUS_ENABLED,
    PARAM_FX_CHORUS_RATE,
    PARAM_FX_CHORUS_DEPTH,
    PARAM_FX_CHORUS_MIX,
    PARAM_FX_DELAY_ENABLED,
    PARAM_FX_DELAY_TIME,
    PARAM_FX_DELAY_FEEDBACK,
    PARAM_FX_DELAY_MIX,
    PARAM_FX_REVERB_ENABLED,
    PARAM_FX_REVERB_SIZE,
    PARAM_FX_REVERB_DAMPING,
    PARAM_FX_REVERB_MIX,

    // Performance
    PARAM_ARP_MODE,
    PARAM_ARP_RATE,
    PARAM_ARP_GATE,
    PARAM_ARP_ENABLED,
    PARAM_PITCH_BEND_RANGE,
    PARAM_MOD_WHEEL_DEPTH,

    // Misc / utility
    PARAM_PANIC,
    PARAM_PARAM_COUNT
} ParamId;

#ifdef __cplusplus
}
#endif

#endif // SYNTH_PARAMS_H
